//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace boilersExtensions.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("boilersExtensions.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Batch update Guid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BatchUpdateGuid {
            get {
                return ResourceManager.GetString("BatchUpdateGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change type from type hierarchy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeTypeFromTypeHierarchy {
            get {
                return ResourceManager.GetString("ChangeTypeFromTypeHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move between #region/#endregion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MoveBetweenRegionAndEndRegion {
            get {
                return ResourceManager.GetString("MoveBetweenRegionAndEndRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open the corresponding line in the GitHub hosting repository に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenGitHubLine {
            get {
                return ResourceManager.GetString("OpenGitHubLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preferences... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename this project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RenameProject {
            get {
                return ResourceManager.GetString("RenameProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename this solution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RenameSolution {
            get {
                return ResourceManager.GetString("RenameSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seed Generator for EFCore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeedGeneratorForEFCore {
            get {
                return ResourceManager.GetString("SeedGeneratorForEFCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update selected Guid string に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateSelectedGuidString {
            get {
                return ResourceManager.GetString("UpdateSelectedGuidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View in Solution Explorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewInSolutionExplorer {
            get {
                return ResourceManager.GetString("ViewInSolutionExplorer", resourceCulture);
            }
        }
    }
}
