//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace boilersExtensions.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("boilersExtensions.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Caption_Cancel {
            get {
                return ResourceManager.GetString("Caption_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Caption_Rename {
            get {
                return ResourceManager.GetString("Caption_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project Name after renaming： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_NewProjectName {
            get {
                return ResourceManager.GetString("Label_NewProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solution Name after renaming： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_NewSolutionName {
            get {
                return ResourceManager.GetString("Label_NewSolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename parent directory of Solution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_WillRenameParentDir {
            get {
                return ResourceManager.GetString("Label_WillRenameParentDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_RenameProject {
            get {
                return ResourceManager.GetString("Title_RenameProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename Solution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_RenameSolution {
            get {
                return ResourceManager.GetString("Title_RenameSolution", resourceCulture);
            }
        }
    }
}
