name: Build extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Add nuget to PATH
      uses: nuget/setup-nuget@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Get version from tag
      id: get_version
      run: |
        try {
          $tag = git describe --tags --abbrev=0
          # タグからvプレフィックスを削除する (例: v3.2.1 → 3.2.1)
          $version = $tag -replace "^v", ""
        } catch {
          # タグが存在しない場合のデフォルトバージョン
          $version = "1.0.0"
        }
        echo "version=$version" >> $env:GITHUB_OUTPUT
    - name: Update version
      run: |
        $version = "${{ steps.get_version.outputs.version }}"
        (Get-Content -Path boilersExtensions\source.extension.vsixmanifest) |
          ForEach-Object {$_ -Replace '1.0.0', $version} |
            Set-Content -Path boilersExtensions\source.extension.vsixmanifest
        (Get-Content -Path boilersExtensions\Properties\AssemblyInfo.cs) |
          ForEach-Object {$_ -Replace '1.0.0', $version} |
            Set-Content -Path boilersExtensions\Properties\AssemblyInfo.cs
        (Get-Content -Path boilersExtensions\boilersExtensions.cs) |
          ForEach-Object {$_ -Replace '1.0.0', $version} |
            Set-Content -Path boilersExtensions\boilersExtensions.cs
    - name: Restore
      run: nuget restore
    - name: Build
      run: msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal
    - uses: actions/upload-artifact@v2
      with:
        name: boilersExtensions.vsix
        path: boilersExtensions\bin\Release\boilersExtensions.vsix
