name: Build extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Add nuget to PATH
      uses: nuget/setup-nuget@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Get version from tag
      id: get_version
      run: |
        $version = "1.0.0"  # デフォルト値
        $tagOutput = $(git tag --list)
        if ($tagOutput) {
          $tag = $(git describe --tags --abbrev=0 2>$null)
          if ($tag) {
            $version = $tag -replace "^v", ""
          }
        }
        echo "version=$version" >> $env:GITHUB_OUTPUT
      shell: pwsh
    - name: Update version
      run: |
        $version = "${{ steps.get_version.outputs.version }}"
        (Get-Content -Path boilersExtensions\source.extension.vsixmanifest) |
          ForEach-Object {$_ -Replace '1.0.0', $version} |
            Set-Content -Path boilersExtensions\source.extension.vsixmanifest
        (Get-Content -Path boilersExtensions\Properties\AssemblyInfo.cs) |
          ForEach-Object {$_ -Replace '1.0.0', $version} |
            Set-Content -Path boilersExtensions\Properties\AssemblyInfo.cs
        (Get-Content -Path boilersExtensions\boilersExtensions.cs) |
          ForEach-Object {$_ -Replace '1.0.0', $version} |
            Set-Content -Path boilersExtensions\boilersExtensions.cs
    - name: Restore
      run: nuget restore
    - name: Build
      run: msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal
    - uses: actions/upload-artifact@v4
      with:
        name: boilersExtensions.vsix
        path: boilersExtensions\bin\Release\boilersExtensions.vsix
